export const data = [

    {
      id: 0,
      name: "Margherita",
      category: "pizza",
      description: "",
      ingredients: ["tomato sauce", "mozzarella"],
      spicy: false,
      vegetarian: true,
      price: 17.0,
      image: "https://i.imgur.com/8B8YLOo.jpg",
quanity : 1,
    },
    {
      id: 1,
      name: "Pepperoni",
      category: "pizza",
      description: "",
      ingredients: ["tomato sauce", "mozzarella", "double pepperoni"],
      spicy: false,
      vegetarian: false,
      price: 20.0,
      image: "https://i.imgur.com/OHHctnf.jpg",
            quanity : 1,
},
    {
      id: 2,
      name: "Rome",
      category: "pizza",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "ham",
        "mushrooms",
        "beef cubes",
      ],
      spicy: false,
      vegetarian: false,
      price: 25.75,
      image: "https://i.imgur.com/3ZTwCfz.png",
            quanity : 1,
},
    {
      id: 3,
      name: "American Spicy",
      category: "pizza",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "pepperoni",
        "tomatoes",
        "green pepper",
        "red onion",
        "jalapenos",
        "Samourai sauce",
      ],
      spicy: true,
      vegetarian: false,
      price: 30.25,
      image: "https://i.imgur.com/dyoOLCO.png",
            quanity : 1,
},
    {
      id: 4,
      name: "Quattro Stagioni",
      category: "pizza",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "ham",
        "pepperoni",
        "mushrooms",
        "green pepper",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/wOEuXuV.jpg",
            quanity : 1,
},
    {
      id: 5,
      name: "Pork & Feta",
      category: "pizza",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "feta cheese",
        "ham",
        "pork cubes",
        "red onion",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/48Zw4K3.png",
            quanity : 1,
},
    {
      id: 6,
      name: "Quattro Formaggi",
      category: "pizza",
      description: "",
      ingredients: [
        "mozzarella",
        "cheddar cheese",
        "emmentaler",
        "blue cheese",
        "oregano",
      ],
      spicy: false,
      vegetarian: true,
      price: 35.15,
      image: "https://i.imgur.com/MDrTvkI.jpg",
            quanity : 1,
},
    {
      id: 7,
      name: "Carnivora",
      category: "pizza",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "chicken breast",
        "beef cubes",
        "pepperoni",
        "bacon",
      ],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/0vPtSSO.png",
            quanity : 1,
},
    {
      id: 8,
      name: "Louisiana Chicken",
      category: "pizza",
      description: "",
      ingredients: [
        "marinated chicken",
        "TABASCO spicy sauce",
        "red pepper sauce",
        "blue cheese",
        "green pepper",
        "red onion",
      ],
      spicy: true,
      vegetarian: false,
      price: 20.0,
      image: "https://i.imgur.com/lZtwJgy.png",
            quanity : 1,
},
    {
      id: 9,
      name: "Honey Mustard Chicken",
      category: "pizza",
      description: "",
      ingredients: [
        "tomato sauce",
        "mozzarella",
        "marinated chicken in Honey Mustard sauce",
        "cheddar cheese",
        "red onion",
      ],
      spicy: false,
      vegetarian: false,
      price: 19.8,
      image: "https://i.imgur.com/SoZu61g.png",
            quanity : 1,
},
    {
      id: 10,
      name: "Hawaiian",
      category: "pizza",
      description: "",
      ingredients: [
        "mozzarella",
        "sweet chilli sauce",
        "pepperoni",
        "pineapple",
        "jalapenos",
        "red onion",
      ],
      spicy: true,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/mqTgvgl.png",
            quanity : 1,
},
    {
      id: 11,
      name: "Classic",
      category: "pizza",
      description: "",
      ingredients: ["tomato sauce", "mozzarella", "ham", "mushrooms", "olives"],
      spicy: false,
      vegetarian: false,
      price: 27.25,
      image: "https://i.imgur.com/k6IGrUd.png",
            quanity : 1,
},

  // ----------------

    {
      id: 12,
      name: "Bolognese",
      category: "pasta",
      description: "",
      ingredients: ["penne", "ragu sauce", "beef cubes", "mozzarella"],
      spicy: false,
      vegetarian: false,
      price: 28.0,
      image: "https://i.imgur.com/IXDJ52k.png",
            quanity : 1,
},
    {
      id: 13,
      name: "Carbonara",
      category: "pasta",
      description: "",
      ingredients: [
        "penne",
        "white cream and garlic sauce",
        "bacon",
        "parmesan",
      ],
      spicy: false,
      vegetarian: true,
      price: 28.0,
      image: "https://i.imgur.com/3jKSuUu.png",
            quanity : 1,
},
  

    {
      id: 14,
      name: "Caesar",
      category: "pasta",
      description: "",
      ingredients: [
        "chicken breast",
        "bacon",
        "parmesan",
        "cherry tomatoes",
        "croutons",
        "lettuce",
        "beetroot",
        "sauce of your choice",
      ],
      spicy: false,
      vegetarian: false,
      price: 20,
      image: "https://i.imgur.com/QWXH2NC.png",
            quanity : 1,
},
    {
      id: 15,
      name: "Greek",
      category: "pasta",
      description: "",
      ingredients: [
        "feta cheese",
        "green olives",
        "cherry tomatoes",
        "cucumbers",
        "red onion",
        "red pepper",
        "oregano",
        "lettuce",
        "beetroot",
        "sauce of your choice",
      ],
      spicy: false,
      vegetarian: true,
      price: 20,
      image: "https://i.imgur.com/qChqf83.png",
            quanity : 1,
},
    {
      id: 16,
      name: "Tuna",
      category: "pasta",
      description: "",
      ingredients: [
        "tuna",
        "green olives",
        "corn",
        "red pepper",
        "red onion",
        "lettuce",
        "beetroot",
        "sauce of your choice",
      ],
      spicy: false,
      vegetarian: false,
      price: 20,
      image: "https://i.imgur.com/Ph0IjrX.png",
            quanity : 1,
},


    {
      id: 17,
      name: "Brownie",
      category: "dessert",
      description: "A delicious cake with chocolate and hazelnuts",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 15,
      image: "https://i.imgur.com/7WbfaDN.png",
            quanity : 1,
},
    {
      id: 18,
      name: "Chocolate Tortilla",
      category: "dessert",
      description: "Tortilla filled with chocolate cream",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 12,
      image: "https://i.imgur.com/Mgsc3IZ.png",
            quanity : 1,
},
    {
      id:19,
      name: "Apple Pie",
      category: "dessert",
      description: "Hot pie with apple and cinnamon",
      ingredients: [],
      spicy: false,
      vegetarian: true,
      price: 15,
      image: "https://i.imgur.com/OWIVhWX.png",
            quanity : 1,
},
    {
      id: 20,
      name: "Cheesecake",
      category: "dessert",
      description: "Cheesecake with berries topping",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 15,
      image: "https://i.imgur.com/AsldA7x.png",
            quanity : 1,
},


    {
      id: 21,
      name: "Coca Cola",
      category: "drinks",
      description: "Coca Cola 330ml",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/nJ6LeWv.png",
            quanity : 1,
},
    {
      id: 22,
      name: "Fanta",
      category: "drinks",
      description: "Fanta 330ml",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/1WDkfme.png",
            quanity : 1,
},
    {
      id: 23,
      name: "Sprite",
      category: "drinks",
      description: "Sprite 330ml",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/qP4Nx1x.jpg",
            quanity : 1,
},
    {
      id: 24,
      name: "Water",
      category: "drinks",
      description: "Dorna 0.5L",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4.5,
      image: "https://i.imgur.com/yYuuaL1.jpg",
            quanity : 1,
},
    {
      id: 25,
      name: "Sparkling water",
      category: "drinks",
      description: "Dorna 0.5L",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4.5,
      image: "https://i.imgur.com/0nyJk19.jpg",
            quanity : 1,
},
    {
      id: 26,
      name: "Fuzetea",
      category: "drinks",
      description: "Fuzetea 0.5L Peach or Lemon",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 5,
      image: "https://i.imgur.com/dsHumXE.jpg",
            quanity : 1,
},


    {
      id: 27,
      name: "BBQ",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/k5Dg7hZ.png",
            quanity : 1,
},
    {
      id: 28,
      name: "Pizza",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/k5Dg7hZ.png",
            quanity : 1,
},
    {
      id: 29,
      name: "Salsa",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: true,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/k5Dg7hZ.png",
            quanity : 1,
},
    {
      id: 30,
      name: "Sweet Chilli",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/k5Dg7hZ.png",
            quanity : 1,
},
    {
      id: 31,
      name: "Spicy TABASCO",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: true,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/k5Dg7hZ.png",
            quanity : 1,
},
    {
      id: 32,
      name: "Mayonnaise",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/OmejA2J.png",
            quanity : 1,
},
    {
      id: 33,
      name: "Ketchup",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/k5Dg7hZ.png",
            quanity : 1,
},
    {
      id: 34,
      name: "Garlic sauce",
      category: "sauces",
      description: "",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 4,
      image: "https://i.imgur.com/OmejA2J.png",
            quanity : 1,
},


    {
      id: 35,
      name: "Wedges",
      category: "sides",
      description: "Baked potatoes, slightly spicy",
      ingredients: [],
      spicy: false,
      vegetarian: true,
      price: 6,
      image: "https://i.imgur.com/sxP6sJt.png",
            quanity : 1,
},
    {
      id: 36,
      name: "Onion rings",
      category: "sides",
      description: "Fried onion rings",
      ingredients: [],
      spicy: false,
      vegetarian: true,
      price: 6,
      image: "https://i.imgur.com/i3Jintb.png",
            quanity : 1,
},
    {
      id: 37,
      name: "Coleslaw",
      category: "sides",
      description: "Cabbage salad, carrots and dressing",
      ingredients: [],
      spicy: false,
      vegetarian: false,
      price: 10,
      image: "https://i.imgur.com/HNX30U9.png",
            quanity : 1,
},

]
